# Uncomment this file to enable multilanguage site support

[en]
languageName = "English"
languagedirection = "ltr"
title = "Blog of WNO-IQ"
weight = 2

[zh-cn]
languageName = "Chinese"
languagedirection = "ltr"
title = "我无IQ的blog"
weight = 1